name: python-script

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/_runner-determinator.yaml
      - .github/workflows/_python-script_check.yaml
      - .github/workflows/scripts/runner_determinator.py

jobs:
  python-script-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: Extract the script from runner_determinator
        run: |
            # Parse the job file, extract the script and run it, up to the final EOF,
            # to generate the python file in the local folder
            yq '.jobs.runner-determinator.steps[] | select(.id == "script") | .run' \
                .github/workflows/_runner-determinator.yaml | sed '/^EOF$/q' | bash

            set +e
            DIFF=$(diff runner_determinator.py .github/workflows/scripts/runner_determinator.py)
            IS_DIFF=$?
            set -e
            if [ $IS_DIFF -eq 0 ]; then
                echo "Scripts are in sync! ^_^";
            else
                echo -e "Scripts are *NOT* in sync:\n ${DIFF}";
                exit 1
            fi