name: Assign issue to the commenter
on:
  repository_dispatch:
    types: [assigntome-command]

jobs:
  assign_issue:
    name: Assign Issue
    runs-on: ubuntu-latest
    steps:
    - name: Show Environment Variables
      run: env
    - name: Show Github Object
      run: |
        cat <<'EOF'
        ${{ toJson(github) }}
        EOF
    - name: Assign Issue
      run: |
        git config --global user.email "andrea.frittoli@gmail.com"
        git config --global user.name "Andrea Frittoli"
        echo $ISSUE_NUMBER
        echo $ASSIGNEE
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/assignees" \
          -f "assignees[]=${ASSIGNEE}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_NUMBER: ${{ github.event.client_payload.github.payload.comment.issue.number }}
        ASSIGNEE: ${{ github.event.client_payload.github.actor }}
