name: Rebase ghstack PRs
on:
  repository_dispatch:
    types: [rebase-command]

jobs:
  ghstack_rebase:
    name: ghstack Rebase
    runs-on: ubuntu-latest
    steps:
    - name: Show Environment Variables
      run: env
    - name: Show Github Object
      run: |
        cat <<'EOF'
        ${{ toJson(github) }}
        EOF
    - name: Show Github Event Path Json
      run: 'cat "$GITHUB_EVENT_PATH" || true'
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.LAND_TOKEN }}
        fetch-depth: '0'
    - uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Check PR can be rebased
      run: |
        pip install requests ghstack
        .github/workflows/scripts/ghstack-perm-check.py rebase <<'EOF'
        ${{ toJson(github) }}
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.LAND_TOKEN }}
    - name: Rebase It!
      run: |
        # Configure Git and GHStack
        git config --global user.email "andrea.frittoli@gmail.com"
        git config --global user.name "Andrea Frittoli"

        cat <<EOF > ~/.ghstackrc
        [ghstack]
        github_url = github.com
        github_oauth = $GITHUB_TOKEN
        github_username = afrittoli
        remote_name = origin
        EOF

        # Checkout the */orig committer branch for rebase 
        # See https://github.com/ezyang/ghstack?tab=readme-ov-file#structure-of-submitted-pull-requests
        HEAD_REF=$(echo '${{ toJson(github) }}' | jq -r .event.client_payload.pull_request.head.ref)
        ORIG_REF=$(printf "$HEAD_REF" | sed 's,/head$,/orig,g')
        git checkout -b rebase-branch "orig/${ORIG_REF}"

        # Do the actual rebase. Git rebase will exit with 1 in case or merge conflicts
        git rebase origin/main

        # Submit the rebased stack to updated the PRs
        ghstack submit
      env:
        GITHUB_TOKEN: ${{ secrets.LAND_TOKEN }}

    - name: Create URL to the run output
      if: ${{ failure() }}
      id: vars
      run: echo "run-url=https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_OUTPUT

    - name: Create comment
      if: ${{ failure() }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.LAND_TOKEN }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
        body: |
          Something went wrong with your `/${{ github.event.client_payload.slash_command.command }}` command: [please check the logs][1].

          [1]: ${{ steps.vars.outputs.run-url }}

    - name: Add reaction
      if: ${{ success() }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.LAND_TOKEN }}
        repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
        comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
        reaction-type: hooray