name: Slash Command Routing
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: route-land
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.LAND_TOKEN }}
        reaction-token: ${{ secrets.LAND_TOKEN }}
        issue-type: pull-request
        permission: write
        commands: |
          land
