name: Slash Command Routing
on:
  issue_comment:
    types: [created]

jobs:
  check_comments:
    runs-on: ubuntu-latest
    steps:
    - name: route-land
      uses: peter-evans/slash-command-dispatch@v3
      with:
        token: ${{ secrets.LAND_TOKEN }}
        reaction-token: ${{ secrets.LAND_TOKEN }}
        config: >
          [
            {
              "command": "land",
              "permission": "write",
              "issue_type": "pull-request",
              "repository": "afrittoli/sandbox"
            },
            {
              "command": "assigntome",
              "permission": "none",
              "issue_type": "issue",
              "repository": "afrittoli/sandbox",
              "static_args": [
                "production",
                "region=us-east-1"
              ]
            }
          ]
